server:
  http2:
    enabled: true
  port: 9001
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.16.96.197:8761/eureka
spring:
  application:
    name: single-customer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

